using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bluent.UI.IconGenerator;

[Generator]
public sealed class FluentIconsGenerator : IIncrementalGenerator
{
    private const string MetadataFileName = "FluentSystemIcons-Resizable.json";
    private static readonly Regex IconRegex = new(
        "\\\"(?<name>ic_fluent_[^\\\"]+_20_(?:regular|filled))\\\"\\s*:\\s*\\d+",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var metadata = context.AdditionalTextsProvider
            .Where(file => string.Equals(Path.GetFileName(file.Path), MetadataFileName, StringComparison.OrdinalIgnoreCase))
            .Select((file, cancellationToken) => file.GetText(cancellationToken)?.ToString() ?? string.Empty);

        context.RegisterSourceOutput(metadata, static (sourceContext, json) =>
        {
            sourceContext.AddSource("FluentIcons.g.cs", SourceText.From(Generate(json), Encoding.UTF8));
        });
    }

    private static string Generate(string json)
    {
        var icons = new SortedDictionary<string, IconPair>(StringComparer.Ordinal);
        var identifiers = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (Match match in IconRegex.Matches(json))
        {
            var fullName = match.Groups["name"].Value;
            var isRegular = fullName.EndsWith("_20_regular", StringComparison.Ordinal);
            var suffix = isRegular ? "_20_regular" : "_20_filled";
            var rawName = fullName["ic_fluent_".Length..^suffix.Length];
            var identifier = ToIdentifier(rawName);

            if (identifiers.TryGetValue(identifier, out var existingName) && !string.Equals(existingName, rawName, StringComparison.Ordinal))
                throw new InvalidOperationException($"Fluent icon names '{existingName}' and '{rawName}' both map to '{identifier}'.");

            identifiers[identifier] = rawName;

            icons.TryGetValue(identifier, out var pair);
            pair = isRegular
                ? pair with { Regular = fullName }
                : pair with { Filled = fullName };
            icons[identifier] = pair;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Bluent.UI.Icons;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Strongly typed catalog generated from the bundled Fluent System Icons metadata.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static partial class FluentIcons");
        builder.AppendLine("{");

        foreach (var (identifier, pair) in icons)
        {
            var regular = pair.Regular ?? pair.Filled;
            if (regular is null)
                continue;

            var filled = pair.Regular is null ? null : pair.Filled;
            builder.Append("    public static IconDefinition ").Append(identifier).Append(" => IconDefinition.FromCss(\"icon-")
                .Append(regular).Append('"');

            if (filled is not null)
                builder.Append(", \"icon-").Append(filled).Append('"');

            builder.AppendLine(");");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ToIdentifier(string rawName)
    {
        var builder = new StringBuilder(rawName.Length);
        var uppercaseNext = true;

        foreach (var character in rawName)
        {
            if (character == '_')
            {
                uppercaseNext = true;
                continue;
            }

            if (!char.IsLetterOrDigit(character))
                continue;

            builder.Append(uppercaseNext ? char.ToUpperInvariant(character) : character);
            uppercaseNext = false;
        }

        if (builder.Length == 0)
            return "Unknown";

        if (char.IsDigit(builder[0]))
            builder.Insert(0, "Icon");

        return builder.ToString();
    }

    private readonly record struct IconPair(string? Regular = null, string? Filled = null);
}
