<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Bluent.UI.Diagrams</PackageId>
        <Title>Bluent UI Diagrams</Title>
        <Authors>Vahid Rassouli</Authors>
        <Description>Blazor diagramming components and tools for interactive business application workflows.</Description>
        <PackageTags>Blazor;Diagrams;Components;Visualization;Business Applications</PackageTags>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/vrassouli/Bluent</PackageProjectUrl>
        <RepositoryUrl>https://github.com/vrassouli/Bluent.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/" />
        <Content Remove="bundleconfig.json;compilerconfig.json" />
        <None Include="bundleconfig.json">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Content Remove="compilerconfig.json" />
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BuildBundlerMinifier2022" Version="2.9.11" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Tools\Drawings\Basic\Abstraction\" />
        <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bluent.Core\Bluent.Core.csproj" />
    </ItemGroup>

</Project>
