name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Publish Blazor app
        run: |
          dotnet publish -c Release -o out
          cp -r out/wwwroot/* ./docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
